apiVersion: apps/v1
kind: Deployment
metadata:
  name: big-brother
spec:
  replicas: 1
  selector:
    matchLabels:
      app: big-brother
  template:
    metadata:
      labels:
        app: big-brother
    spec:
      containers:
        - name: big-brother
          image: docker.io/keanuwatts/theclusterflux:BigBrother
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: big-brother
spec:
  selector:
    app: big-brother
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: big-brother
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - big-brother.theclusterflux.com
    secretName: theclusterflux
  rules:
  - host: big-brother.theclusterflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: big-brother
            port:
              number: 8080
